<?php

/**
 * @file
 * Contains simple_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8module_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_module module.
    case 'help.page.simple_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A simple module') . '</p>';
      return $output;

    default:
  }
}

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function d8module_example_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Chamado em todos os forms, duas vezes.
  // Uma quando o form vai ser exibido para o usuário
  // E outra depois de o usuário clicar no submit do form.
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function d8module_example_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['best_animal'] = [
    '#type' => 'radios',
    '#title' => t('What is the best animal?'),
    '#options' => [t('Cat'), t('Dog'), t('Lhama'), t('Dragon'), t('Lizard')],
  ];
  $form['#validate'][] = 'd8module_example_best_animal_validate_form';
}

/**
 * Validate the best_animal.
 */
function d8module_example_best_animal_validate_form(array &$form, FormStateInterface $form_state) {
  if ($form_state->getValue('best_animal') != 0) {
    $form_state->setErrorByName('best_animal', t('Sorry, wrong animal.'));
  }
}
