<?php

/**
 * @file
 * Contains simple_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function d8module_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_module module.
    case 'help.page.simple_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A simple module') . '</p>';
      return $output;

    default:
  }
}

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
// function d8module_example_form_alter(&$form,$form_state, $form_id) {

//   if ($form_id == 'user_login_form') {
//     $form['best_animal'] = [
//       '#type' => 'radios',
//       '#title' => t('Whats the best animal'),
//       '#options' => [t('Cat'), t('Dog'), t('Lhama'), t('Dragon')],
//     ];
//   }
// }

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function d8module_example_form_user_login_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['best_animal'] = [
      '#type' => 'radios',
      '#title' => t('Whats the best animal'),
      '#options' => [t('Cat'), t('Dog'), t('Lhama'), t('Dragon'), t('Lizard')],
    ];
  }
}
